name: Build app

on:
 workflow_dispatch:
 workflow_call:
 push:
    branches:
      - main # default branch
    paths:
      - electron-static/**/**
      - Genshin-Impact-Wish-Simulator/src-tauri/**/**
 pull_request:
    branches:
      - main # default branch
    paths:
      - electron-static/**/**
      - Genshin-Impact-Wish-Simulator/src-tauri/**/**


jobs:
  Page:
    name: Build page
    uses: ./.github/workflows/page.yml
  Build-app:
    name: Build app with Electron
    needs: Page
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest,ubuntu-latest,macos-latest,macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4.1.0
        with:
          node-version: "20"
      - name: Cache NPM dependencies
        uses: actions/cache@v4.0.2
        with:
          path: ./electron-static/node_modules
          key: ${{ matrix.os }}-npm-app-cache
          restore-keys: |
            ${{ matrix.os }}-npm-app-cache
      - name: Install Dependencies
        run: |
         cd electron-static
         yarn install
      - name: Download Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: frontend
      - name: extract new
        run: |          
         7z x frontend.zip -oelectron-static/ -y
      - name: Build
        run: |
         cd electron-static
         yarn run build
      - name: Package (${{ matrix.os }})
        run: |
         cd electron-static
         7z a -tzip hsr-picker-${{ runner.os }}-${{ runner.arch }}.zip ./hsr-*
      - name: Upload (${{ matrix.os }})
        uses: actions/upload-artifact@v4.3.1
        with:
          name: hsr-picker-${{ matrix.os }}
          path: electron-static/hsr-picker-${{ runner.os }}-${{ runner.arch }}.zip
      - name: Remove old
        if: false
        run: |
         cd electron-static
         rm -rf static