name: Release Tools 

on:
 workflow_dispatch:
 push:
   tags:
     - "tool-*"
jobs:
  app:
    name: Build tools
    uses: ./.github/workflows/py.yml
  release:
    needs: app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Download Artifact
        uses: actions/download-artifact@v4.1.4
      - name: Create Release
        uses: softprops/action-gh-release@v2.2.0
        with:
            files: ./**/image-processor*.*